version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        WORKDIR: workspace
    ports:
      - 8000:8000
    volumes:
      - .:/workspace:cached
    depends_on:
      - mongo

    command: /bin/sh -c "while sleep 1000; do :; done"
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
